# Generated by Django 4.2.6 on 2023-10-24 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserData',
            new_name='UserDat',
        ),
    ]
