# Generated by Django 4.2.6 on 2023-10-27 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_rename_firstname_userdat_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdat',
            old_name='first_name',
            new_name='firstname',
        ),
    ]
