# Generated by Django 4.2.6 on 2023-10-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_rename_first_name_userdat_firstname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdat',
            old_name='firstname',
            new_name='first_name',
        ),
    ]
